### ISSUE TITLE
urllib HTTPError

### ISSUE THREAD

**Issue by kurapan** [facebookresearch/fvcore#14]
Hi!
I've tried to run Detectron2 demo and when I executed it for the first time, it ran until a point where it loads an image (I gave it a wrong path in the argument so the execution stopped).
When I fixed it and tried running it for the second time, I repeatedly encountered HTTPError, which occurred in fvcore package. I post the traceback below.
Is there any restriction on automatic downloads by fvcore? 

```
[12/05 18:23:44 detectron2]: Arguments: Namespace(confidence_threshold=0.5, config_file='configs/COCO-InstanceSegmentation/mask_rcnn_R_101_FPN_3x.yaml', input=['/home/kurapan/Datasets/YFCC100M/111/aac/111aac90261da6d67961cec95367b21a.jpg'], opts=['MODEL.WEIGHTS', 'detectron2://COCO-InstanceSegmentation/mask_rcnn_R_101_FPN_3x/137849600/model_final_f10217.pkl'], output=None, video_input=None, webcam=False)
WARNING [12/05 18:23:44 d2.config.compat]: Config 'configs/COCO-InstanceSegmentation/mask_rcnn_R_101_FPN_3x.yaml' has no VERSION. Assuming it to be compatible with latest v2.
model_final_f10217.pkl: 0.00B [00:01, ?B/s]
Failed to download https://dl.fbaipublicfiles.com/detectron2/COCO-InstanceSegmentation/mask_rcnn_R_101_FPN_3x/137849600/model_final_f10217.pkl
Traceback (most recent call last):
  File "demo/demo.py", line 73, in <module>
    demo = VisualizationDemo(cfg)
  File "/home/kurapan/Code/3rdparty/repos/detection/detectron2/demo/predictor.py", line 35, in __init__
    self.predictor = DefaultPredictor(cfg)
  File "/home/kurapan/Code/3rdparty/repos/detection/detectron2/detectron2/engine/defaults.py", line 161, in __init__
    checkpointer.load(cfg.MODEL.WEIGHTS)
  File "/home/kurapan/miniconda3/envs/detectron/lib/python3.7/site-packages/fvcore/common/checkpoint.py", line 99, in load
    path = PathManager.get_local_path(path)
  File "/home/kurapan/miniconda3/envs/detectron/lib/python3.7/site-packages/fvcore/common/file_io.py", line 529, in get_local_path
    )._get_local_path(path, **kwargs)
  File "/home/kurapan/Code/3rdparty/repos/detection/detectron2/detectron2/checkpoint/catalog.py", line 125, in _get_local_path
    return PathManager.get_local_path(self.S3_DETECTRON2_PREFIX + name)
  File "/home/kurapan/miniconda3/envs/detectron/lib/python3.7/site-packages/fvcore/common/file_io.py", line 529, in get_local_path
    )._get_local_path(path, **kwargs)
  File "/home/kurapan/miniconda3/envs/detectron/lib/python3.7/site-packages/fvcore/common/file_io.py", line 404, in _get_local_path
    cached = download(path, dirname, filename=filename)
  File "/home/kurapan/miniconda3/envs/detectron/lib/python3.7/site-packages/fvcore/common/download.py", line 62, in download
    url, filename=tmp, reporthook=hook(t)
  File "/home/kurapan/miniconda3/envs/detectron/lib/python3.7/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/home/kurapan/miniconda3/envs/detectron/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/home/kurapan/miniconda3/envs/detectron/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/home/kurapan/miniconda3/envs/detectron/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/home/kurapan/miniconda3/envs/detectron/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/home/kurapan/miniconda3/envs/detectron/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/home/kurapan/miniconda3/envs/detectron/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

**Comment by ppwwyyxx** [comment]
You set `MODEL.WEIGHTS` to an invalid URL. You can find URLs to the correct model in https://github.com/facebookresearch/detectron2/blob/master/MODEL_ZOO.md

**Comment by kurapan** [comment]
Oh, I'm an idiot. Thank you.
