### ISSUE TITLE
Can I install fvcore on Win10

### ISSUE THREAD

**Issue by Hemingwaycn** [facebookresearch/fvcore#4]

**Comment by ppwwyyxx** [comment]
Have not tried, but I think you can

**Comment by FedorZaytsev** [comment]
```
titanx@DESKTOP-D6PSBRM C:\Users\titanx>pip install 'https://github.com/facebookr
esearch/fvcore'                                                                 
ERROR: Invalid requirement: "'https://github.com/facebookresearch/fvcore'" 
```

**Comment by ppwwyyxx** [comment]
Could you try the command in the [README](https://github.com/facebookresearch/fvcore) instead?

**Comment by FedorZaytsev** [comment]
Oh, sorry, I copied wrong output. Originally I tried the command in the README:

```
titanx@DESKTOP-D6PSBRM C:\Users\titanx>pip install 'git+https://github.com/faceb
ookresearch/fvcore'                                                             
ERROR: Invalid requirement: "'git+https://github.com/facebookresearch/fvcore'" 
```


The workaround that I found:
```
git clone git@github.com:facebookresearch
/fvcore.git
cd fvcore
pip install .
```

**Comment by ppwwyyxx** [comment]
The command does work on linux. Either your pip is too old, or it's some limitation of windows.

**Comment by waynemu95** [comment]
me too, when I use detectron2

**Comment by SumanthReddyKaliki** [comment]
Even I'm having the same issue when I try to install on Windows 10

```
pip install 'git+https://github.com/faceb
ookresearch/fvcore'                                                             
ERROR: Invalid requirement: "'git+https://github.com/facebookresearch/fvcore'" 
```

**Comment by bluesheepcj** [comment]
> git clone git@github.com:facebookresearch/fvcore.git
> cd fvcore
> pip install .

It's work for me, thank you

**Comment by xavialex** [comment]
Hi all. I ran into this error when trying to install fvcore in Windows through conda:

`    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\festevem\AppData\Local\Continuum\anaconda3\envs\detectron2\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\festevem\\AppData\\Local\\Temp\\pip-install-x3uey11e\\pycocotools\\setup.py'"'"'; __file__='"'"'C:\\Users\\festevem\\AppData\\Local\\Temp\\pip-install-x3uey11e\\pycocotools\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: C:\Users\festevem\AppData\Local\Temp\pip-install-x3uey11e\pycocotools\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\festevem\AppData\Local\Continuum\anaconda3\envs\detectron2\lib\tokenize.py", line 447, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\festevem\\AppData\\Local\\Temp\\pip-install-x3uey11e\\pycocotools\\setup.py'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.`

Simply [install shapely](https://anaconda.org/search?q=platform%3Awin-64+Shapely) to avoid it.

**Comment by iiwolf** [comment]
Had the same exact error and have been trying to figure out a solution for the last hour. `conda install shapely` did the trick! Thanks @xavialex !!

**Comment by xkszltl** [comment]
Single quote is for bash, cmd wants double quote instead.

**Comment by Terizian** [comment]
I can confirm that it works on Windows 10. I've just had to manually install dependencies from PyPI as I'm doing an offline installation.

**Comment by hamidjon1376** [comment]
> Single quote is for bash, cmd wants double quote instead.

Hi,
Thanks alot
it is the best resolve

**Comment by dsreepat** [comment]
> > Single quote is for bash, cmd wants double quote instead.
> 
> Hi,
> Thanks alot
> it is the best resolve

this works!!

**Comment by harshakvs** [comment]
`git clone https://github.com/facebookresearch/fvcore.git
cd fvcore
pip install  . `

Worked for me! Thanks!
