### ISSUE TITLE
TypeError: _get_local_path() got an unexpected keyword argument 'force'

### ISSUE THREAD

**Issue by cjongseok** [facebookresearch/fvcore#62]
Hi guys,

Thanks for the great project 🙏 
I've faced with it while running my usual colab project and it was resolved after downgrading fvcore `0.1.4` -> `0.1.3.post20210317`.

It seems  `get_local_path()` doesn't call ` _get_local_path()` of `iopath` `0.1.7`.
It's an environmental issue?

Test Environment
---
fvcore: 0.1.4
python: 3.7
iopath: 0.1.7
...

Stack Trace
---
```
...
  File "/usr/local/lib/python3.7/dist-packages/fvcore/common/checkpoint.py", line 140, in load
    path = self.path_manager.get_local_path(path)
  File "/usr/local/lib/python3.7/dist-packages/fvcore/common/file_io.py", line 157, in get_local_path
    path, force=force, **kwargs
TypeError: _get_local_path() got an unexpected keyword argument 'force'

```

**Comment by caniko** [comment]
I too got this error today.

Stack trace:
```
Traceback (most recent call last):
File "/home/admin/.local/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 20, in _wrap
fn(i, *args)
File "/home/admin/detectron2_repo/detectron2/engine/launch.py", line 125, in _distributed_worker
main_func(*args)
File "/home/admin/meshrcnn/tools/train_net.py", line 95, in main
trainer.resume_or_load(resume=args.resume)
File "/home/admin/detectron2_repo/detectron2/engine/defaults.py", line 408, in resume_or_load
self.checkpointer.resume_or_load(self.cfg.MODEL.WEIGHTS, resume=resume)
File "/home/admin/.local/lib/python3.6/site-packages/fvcore/common/checkpoint.py", line 215, in resume_or_load
return self.load(path, checkpointables=[])
File "/home/admin/detectron2_repo/detectron2/checkpoint/detection_checkpoint.py", line 52, in load
ret = super().load(path, *args, **kwargs)
File "/home/admin/.local/lib/python3.6/site-packages/fvcore/common/checkpoint.py", line 140, in load
path = self.path_manager.get_local_path(path)
File "/home/admin/.local/lib/python3.6/site-packages/iopath/common/file_io.py", line 1100, in get_local_path
path, force=force, **kwargs
TypeError: _get_local_path() got an unexpected keyword argument 'force'
```

**Comment by caniko** [comment]
It seems that the PyPi package of `iopath` is out of sync with `fvcore`s PyPi package. I am pretty certain as because `_get_local_path()` has the kwarg named `force` in the github repository, but the package from PyPi does not.

Solve by installing iopath from the repository:
```
pip install "git+https://github.com/facebookresearch/iopath"
```
