### ISSUE TITLE
RuntimeError in ParamScheduler

### ISSUE THREAD

**Issue by krishnamoorthybabu** [facebookresearch/fvcore#81]
Encountered an runtime error when running with latest version of detectron2 and fvcore. Happens exactly when training the object detection model with scheduler.step() in code.

File "/powerplant/workspace/cflkmb/AIP/leafroll-detection/lib/computer-vision/pfr-vision/env/pytorch_gpu/lib/python3.8/site-packages/fvcore/common/param_scheduler.py", line 236, in `__call__`
      `raise RuntimeError(
  RuntimeError: where in ParamScheduler must be in [0, 1]: got 1.1666666666666667`

**library with version**
* torch                     1.9.0+cu111
* torchaudio                0.9.0
* torchvision               0.10.0+cu111
* detectron2                0.5+cu111
* fvcore                    0.1.5

**Comment by aerinkim** [comment]
Same. torch 1.9.0 +cu11.2

**Comment by JJC6050** [comment]
Getting the same error.Have you solved this problem now? How did you solve it?
Traceback (most recent call last):
  File "tools/train_net.py", line 226, in <module>
    launch(
  File "f:\cocoapi\detectron2-0.4\detectron2\engine\launch.py", line 62, in launch
    main_func(*args)
  File "tools/train_net.py", line 214, in main
    trainer = Trainer(cfg)
  File "f:\cocoapi\detectron2-0.4\detectron2\engine\defaults.py", line 323, in __init__
    self.scheduler = self.build_lr_scheduler(cfg, optimizer)
  File "f:\cocoapi\detectron2-0.4\detectron2\engine\defaults.py", line 474, in build_lr_scheduler
    return build_lr_scheduler(cfg, optimizer)
  File "f:\cocoapi\detectron2-0.4\detectron2\solver\build.py", line 246, in build_lr_scheduler
    sched = WarmupParamScheduler(
  File "f:\cocoapi\detectron2-0.4\detectron2\solver\lr_scheduler.py", line 37, in __init__
    end_value = scheduler(warmup_length)  # the value to reach when warmup ends
  File "E:\Anaconda\envs\detectron2\lib\site-packages\fvcore\common\param_scheduler.py", line 236, in __call__
    raise RuntimeError(
RuntimeError: where in ParamScheduler must be in [0, 1]: got 5.0

**Comment by wanghuajia** [comment]
I got the simmilar error, and I foun the bug. I have set two dataloader, so the learing rate would increase twice which  cause over 1.

**Comment by sseerreenn** [comment]
> I got the simmilar error, and I foun the bug. I have set two dataloader, so the learing rate would increase twice which cause over 1.

Hi, I think I have the same issue, where did you find the two dataloader and how did you solve it?

**Comment by azuryl** [comment]
me 2

**Comment by cmj18** [comment]
how to solve it?

**Comment by rachel-liu-0104** [comment]
same. anyone got any solutions?

**Comment by SangbumChoi** [comment]
For me it was the problem of registering hook twice in Trainer which cause doubling current iteration

```
class Trainer(DefaultTrainer):
    """
    We use the "DefaultTrainer" which contains a number pre-defined logic for
    standard training workflow. They may not work for you, especially if you
    are working on a new research project. In that case you can use the cleaner
    "SimpleTrainer", or write your own training loop.
    """

    def __init__(self, cfg):
        """
        Args:
            cfg (CfgNode):
        """
        super().__init__(cfg)
        logger = logging.getLogger("detectron2")
        if not logger.isEnabledFor(logging.INFO):  # setup_logger is not called for d2
            setup_logger()
        cfg = DefaultTrainer.auto_scale_workers(cfg, comm.get_world_size())

        # Assume these objects must be constructed in this order.
        model = self.build_model(cfg)
        optimizer = self.build_optimizer(cfg, model)
        data_loader = self.build_train_loader(cfg)

        model = create_ddp_model(model, broadcast_buffers=False)
        if cfg.DEBUG.TRACK_IMAGES:
            self._trainer = (DebugAMPTrainer if cfg.SOLVER.AMP.ENABLED else DebugSimpleTrainer)(
                model, data_loader, optimizer
            )
        else:
            self._trainer = (AMPTrainer if cfg.SOLVER.AMP.ENABLED else SimpleTrainer)(
                model, data_loader, optimizer
            )

        # self.scheduler = self.build_lr_scheduler(cfg, optimizer)
        # self.checkpointer = DetectionCheckpointer(
        #     # Assume you want to save checkpoints together with logs/statistics
        #     model,
        #     cfg.OUTPUT_DIR,
        #     trainer=weakref.proxy(self),
        # )
        # self.register_hooks(self.build_hooks()) <- Do not implement twice since DefaultTrainer already calls once

```

**Comment by KEJie97** [comment]
You can try increasing the value of parameter `train.max_iter`, such as 1000.
